/**
 * API Service - Unified Data Access Layer
 * ES6 Module with Tauri Commands Support
 * Generated by Antigravity
 * 
 * 迁移说明：
 * - 正在迁移到统一 API 客户端 (apiClient)
 * - 过渡期保留 HTTP fallback 支持
 * - 最终目标：纯 Rust 后端，移除 HTTP fallback
 */

import { invokeCommand } from '../utils/tauri-api.js';
import { apiClient } from '../core/api-client.js';

// Tauri API import for production builds
// Import from @tauri-apps/api for production, fallback to window.__TAURI__ for dev
import { invoke as tauriApiInvoke } from '@tauri-apps/api/core';

// Helper function to get invoke - tries both methods
const getTauriInvoke = () => {
  // Try imported API first (production)
  if (typeof tauriApiInvoke === 'function') {
    return tauriApiInvoke;
  }
  // Fallback to global API (development with withGlobalTauri)
  if (window.__TAURI__?.core?.invoke) {
    return window.__TAURI__.core.invoke;
  }
  return null;
};

const KEYS = {
  ORDERS: 'erp.orders',
  CUSTOMERS: 'erp.customers',
  COMPANY: 'erp.company',
  ORDER_DRAFT: 'erp.order_draft',
  DOCS_STYLE: 'erp.docs.style',
};

function getCookie(name) {
  if (typeof document === 'undefined') return undefined;
  const match = document.cookie.match(new RegExp('(?:^|; )' + name.replace(/([.$?*|{}()\[\]\\\/\+^])/g, '\\$1') + '=([^;]*)'));
  return match ? decodeURIComponent(match[1]) : undefined;
}

function isTauriLikeEnv() {
  try {
    if (typeof window !== 'undefined') {
      if (window.__TAURI__) return true;
    }
    const p = String(window.location.protocol || '').toLowerCase();
    if (p === 'tauri:' || p === 'file:') return true;
    const host = String(window.location.hostname || '').toLowerCase();
    if (host === 'tauri.localhost') return true;
  } catch (_) { }
  return false;
}

const API_BASE_URL = isTauriLikeEnv() ? 'http://127.0.0.1:3000' : '';

async function request(url, opts) {
  let requestUrl = url;
  if (url.startsWith('/')) {
    requestUrl = API_BASE_URL + url;
  }

  const method = ((opts && opts.method) || 'GET').toUpperCase();
  const headers = Object.assign({}, (opts && opts.headers) || {});

  // Authorization handling
  try {
    const token = localStorage.getItem('token');
    if (token && !headers['Authorization'] && !headers['authorization']) {
      headers['Authorization'] = `Bearer ${token}`;
    }
  } catch (err) { /* ignore */ }

  if (method !== 'GET' && method !== 'HEAD') {
    const csrf = getCookie('csrf_token');
    if (csrf) {
      headers['x-csrf-token'] = csrf;
    }
  }

  const newOpts = Object.assign({}, opts, { headers });

  if (method !== 'GET' && method !== 'HEAD' && !newOpts.credentials) {
    newOpts.credentials = 'include';
  }

  return fetch(requestUrl, newOpts);
}

async function json(url, opts) {
  try {
    const response = await request(url, opts);

    if (!response.ok) {
      // Try to parse error message
      let msg = 'Request failed';
      try {
        const errData = await response.json();
        msg = errData.message || msg;
      } catch (e) {
        msg = response.statusText || msg;
      }
      const error = new Error(msg);
      error.status = response.status;
      throw error;
    }

    // Check for 204 No Content
    if (response.status === 204) return null;

    return await response.json();
  } catch (err) {
    console.error('API Fetch Error:', err);
    throw err;
  }
}

// ----------------------------------------------------------------------
// API Mockules
// ----------------------------------------------------------------------

import { orders } from './modules/orders.js';

import { customers } from './modules/customers.js';
import { forwarders } from './modules/forwarders.js'; // 新增货代模块
import { products } from './modules/products.js';
import { users } from './modules/users.js';
import { auth } from './modules/auth.js';
import { company } from './modules/company.js';
import { orderConfigs } from './modules/orderConfigs.js';
import { storage } from './modules/storage.js';
import { documentCenter } from './modules/documentCenter.js';
import { dashboard } from './modules/dashboard.js';
import { reminders } from './modules/reminders.js';
import { logs } from './modules/logs.js';
import { diagnostics } from './modules/diagnostics.js';























export const ApiService = {
  json,
  request,
  orders,
  customers,
  forwarders, // 新增货代模块
  products,
  users,
  auth,
  company,
  orderConfigs,
  storage,
  documentCenter,
  dashboard,
  reminders,
  logs,
  diagnostics,
  KEYS
};

export default ApiService;
window.ApiService = ApiService;
